// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm6U_A33jJMK2tiZGeXp-y-JgNjtO5gq0',
    appId: '1:740492095993:web:092c9fb7f7117f15778d28',
    messagingSenderId: '740492095993',
    projectId: 'connect-chat-e68f5',
    authDomain: 'connect-chat-e68f5.firebaseapp.com',
    storageBucket: 'connect-chat-e68f5.appspot.com',
    measurementId: 'G-B06KFMZVJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLX46aLNjEVDHXSOsDpPSLnzDbulQhjyg',
    appId: '1:740492095993:android:f1c954b73161ae27778d28',
    messagingSenderId: '740492095993',
    projectId: 'connect-chat-e68f5',
    storageBucket: 'connect-chat-e68f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4EreW54pLnrA7Hht3YDSDf1RgBpkYcpI',
    appId: '1:740492095993:ios:b9e66a93e9ddd330778d28',
    messagingSenderId: '740492095993',
    projectId: 'connect-chat-e68f5',
    storageBucket: 'connect-chat-e68f5.appspot.com',
    iosClientId: '740492095993-3fq9o69rpqo1o3ssk8bljaom9v76fnub.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
